
title: Karim de Fombelle's Notes
email: karim.defombele@gmail.com
description: >- # The description for your site
  A few notes of my developer journey to stay tuned
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kdefombelle.github.io"
twitter_username: karimdefombelle
github_username:  kdefombelle

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
